### ISSUE TITLE
Doc: Use Case pxe server

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-srv_tftp#2]
Documenting the pxe setup would be a nice addition. Basically srv_dhcp with some params + srv_tftp.

See also: https://github.com/while-true-do/ansible-role-srv_dhcp/issues/2

**Comment by daniel-schier** [comment]
example for dhcp role:

#### PXE Server Setup

Configure a dhcp server and tftp server as pxe boot service. You need the
[while_true_do.srv_tftp](https://github.com/while-true-do/ansible-role-srv_tftp)
Role.

```
- hosts: install
  roles:
    - role: while_true_do.srv_tftp
      wtd_srv_tftp_boot_conf:
      timeout: "100"
      labels:
        - label: "CentOS 7.6"
          default: true
          kernel: "centos76/vmlinuz"
          append: "initrd=centos76/initrd.img"
    - role: while_true_do.srv_dhcp
      wtd_srv_dhcp_conf_global:
        allow_booting: false
        allow_bootp: false
        next_server: "<ip of install host>"
        filename: "pxelinux.cfg/default"
      wtd_srv_dhcp_conf_networks:
        - name: "my network"
          subnet: "192.168.0.0"
          netmask: "255.255.255.0"
          domain_name_servers: "192.168.0.1"
          routers: "192.168.0.1"
          range: "192.168.0.10 192.168.0.20"
```
